# Generated by Django 4.0.4 on 2022-07-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_sent', models.DateField(blank=True, null=True, verbose_name='Date sent')),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('p', 'Pending...'), ('a', 'Accepted'), ('r', 'Rejected')], default='p', max_length=1)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='@privateemail or @gmail', max_length=70)),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='Date Joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='Campaign', max_length=25, verbose_name='Email subject')),
                ('type', models.CharField(choices=[('h', 'html'), ('p', 'plain text')], max_length=1)),
                ('body', models.TextField()),
                ('camp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.campaign', verbose_name='Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='@privateemail or @gmail', max_length=60)),
                ('password', models.CharField(help_text='Your password will be encrypted', max_length=500)),
                ('smtp_server', models.CharField(default='mail.privateemail.com', help_text='smtp.domain.com', max_length=60, verbose_name='Smtp server')),
                ('port', models.CharField(default='587', max_length=10, verbose_name='Email port')),
                ('tls', models.BooleanField(default=True, verbose_name='Email use TLS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Sender's email",
                'verbose_name_plural': "Sender's emails",
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='from_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_related', to='messenger.email', verbose_name="Sender's emails"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='to_emails',
            field=models.ManyToManyField(related_name='campaigns_related', to='messenger.subscriber', verbose_name='To'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
